# Site settings
title: Coding: A History
description: A blog about my coding journey for self-reflection and rememberance
# baseurl:
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: skywardcode
user_description: learning to code by a self-curated path
user_title: Web Developer
email: contact me via GitHub

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
